services:
  - type: web
    name: gemini-alternative-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: reflex run --env prod --single-port --backend-host 0.0.0.0 --frontend-port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gemini-alternative-db
          property: connectionString
databases:
  - name: gemini-alternative-db
    plan: free
